# Generated by Django 4.2.7 on 2025-06-17 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BubbleSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=50)),
                ('start_time', models.DurationField()),
                ('end_time', models.DurationField()),
                ('text', models.TextField()),
                ('bubble_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bubbles.bubblesection')),
            ],
            options={
                'unique_together': {('bubble_section', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Bubble',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=50)),
                ('layer', models.CharField(max_length=10)),
                ('bubble_name', models.CharField(max_length=100)),
                ('start_time', models.DurationField()),
                ('stop_time', models.DurationField()),
                ('color', models.CharField(max_length=7)),
                ('bubble_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubbles', to='bubbles.bubblesection')),
            ],
            options={
                'unique_together': {('bubble_section', 'external_id')},
            },
        ),
    ]
