# Generated by Django 4.2.7 on 2025-08-08 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import datetime


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bubbles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bubble',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bubble',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('song_hash', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'song_hash')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bubble',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bubble',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubbles', to='bubbles.song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bubbles.song'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bubble',
            unique_together={('song', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('song', 'external_id')},
        ),
        migrations.RemoveField(
            model_name='bubble',
            name='bubble_section',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='bubble_section',
        ),
        migrations.DeleteModel(
            name='BubbleSection',
        ),
    ]
