# Generated by Django 4.2.7 on 2025-06-04 21:13
# Modified my Remington

from django.db import migrations, models
from datetime import timedelta

def set_trial_end_date(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.filter(trial_end_date__isnull=True):
        user.trial_end_date = user.date_joined + timedelta(days=30)
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='User',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='User',
            name='trial_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(set_trial_end_date, reverse_code=migrations.RunPython.noop),
    ]
