# Generated by Django 4.2.7 on 2025-06-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_trial_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialFingerprint',
            fields=[
                ('fingerprint', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('trials_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
